### ISSUE TITLE
security token expired errors after several hours on EC2

### ISSUE THREAD

**Issue by chanind** [DavidMuller/aws-requests-auth#27]
I'm using this library in EC2 to connect to elasticsearch via the python elasticsearch library. This works fine for several hours but then all requests start failing with 403 `The security token included in the request is expired` errors. It seems like whatever token this library is using is expiring and the library isn't handling requesting a new token. I'm using credentials pulled from the `boto3` session.

**Comment by DavidMuller** [comment]
Hi @chanind that behavior you're describing sounds possible. `aws-requests-auth` does nothing to refresh or otherwise renew the credentials you pass to it. Whatever credentials you give it are the credentials that will be used to sign requests until the class instance is destroyed.

There are a number of different approaches you can take to build something that ensures your credentials don't expire including adjusting how you provision IAM roles in AWS. Something I stumbled upon recently is [a wrapper that Yelp build around `AWSRequestsAuth` called `RefeshableAWSRequestsAuth`](https://github.com/Yelp/elastalert/blob/9de65e0acbe0853108743e870b24fb199064e2e0/elastalert/auth.py).  You might be able to leverage ideas in [that file](https://github.com/Yelp/elastalert/blob/9de65e0acbe0853108743e870b24fb199064e2e0/elastalert/auth.py) to build something for your own use.

**Comment by DavidMuller** [comment]
You can also checkout a recent addition to this package (`BotoAWSRequestsAuth`) which @tobiasmcnulty contributed in https://github.com/DavidMuller/aws-requests-auth/pull/29

It may help with your expiring credentials problem -- find full details at the bottom of the README

**Comment by chanind** [comment]
Awesome! Looks great! Thanks for adding this
