### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [DavidMuller/aws-requests-auth#49]
First off, thanks for a great library!

I'm writing some unit tests on a package that makes use of your library, and I've got a method called `validate_auth` that simply pings an endpoint at which authentication is required. I can mock out the endpoint's response, but I'm having trouble knowing how to mock out `BotoAWSRequestsAuth`. Could you offer any guidance on what the best approach might be? 

I'm wondering if perhaps using boto's [stubber](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html) is the best approach?

**Comment by DavidMuller** [comment]
Are you having issues with `BotoAWSRequestsAuth` inadvertently hitting the network?

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
I'm getting
```
  File "some_path/venv/lib/python3.7/site-packages/aws_requests_auth/boto_utils.py", line 24, in get_credentials
    frozen_credentials = credentials_obj.get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
```

I'm expecting this code to run (in production) on an AWS instance that has the proper IAM role attached to it, so I'm leveraging [automatic credentials gathering](https://github.com/DavidMuller/aws-requests-auth#using-boto-to-automatically-gather-aws-credentials). 

In my unit tests those don't exist, so maybe I need to also mock `get_frozen_credentials`?

**Comment by DavidMuller** [comment]
Ah I see. Yeah I think you have a few options...

- Patch `Session.get_credentials()` so that it returns a mock object
- Make your "test machine" bootstrap a "fake" aws credentials file or fake aws credentials in env vars...so that `BotoAWSRequestsAuth` picks up some credentials even if those credentials would never successfully authenticate. 
- Have your test code use `AWSRequestsAuth` instead of `BotoAWSRequestsAuth` (so that you can just hardcode fake credentials) instead of having `BotoAWSRequestsAuth` / `boto` try to look up something on its own
- etc.

I don't know much about your test environment, or your setup, but whatever solution helps keep you from accidentally authing to AWS in tests and gets this request signing library out of the way as quick as possible would probably be preferrable

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Great, thanks for the help! For those that stumble here somehow, I ended up mocking the AWS environment variables with

```python
# conftest.py

@pytest.fixture
def mock_env_aws_auth(monkeypatch):
    """
    Authentication expects there be AWS credentials available
    in the environment variables; this won't be the case when running tests
    on travis, so we mock them here.

    """
    monkeypatch.setenv("AWS_ACCESS_KEY_ID", "mock_key_id")
    monkeypatch.setenv("AWS_SECRET_ACCESS_KEY", "mock_secret")

@pytest.fixture
def mock_auth(requests_mock, mock_env_aws_auth):
    # requests_mock comes from https://pypi.org/project/requests-mock/
    url = "some_url_that_requires_auth"
    requests_mock.get(url, status_code=200)

# test_something.py

def test_auth(mock_auth):
    # now we can authenticate with our mocked object
    auth = Api.validate_auth() # Api is just some class with a method validate_auth()
```
